version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev # You can also use Dockerfile if suitable
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
    tty: true

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
