name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests (optional)
        run: |
          docker build -t test-image -f Dockerfile.dev .
          docker run --rm -e CI=true test-image npm test

      - name: Create deployment package
        run: |
          zip -r deploy.zip . -x '*.git*' 'node_modules/*' '*.DS_Store'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-1-133024290311
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
